/*
 *
 * Donations constants
 *
 */

enum DonationsConstants {
  DEFAULT_ACTION = 'app/Donations/DEFAULT_ACTION',
  GET_DONATIONS = 'app/Donations/GET_DONATIONS',
  GET_DONATIONS_SUCCESS = 'app/Donations/GET_DONATIONS_SUCCESS',
  GET_DONATIONS_FAIL = 'app/Donations/GET_DONATIONS_FAIL',
  CREATE_DONATION = 'app/Donations/CREATE_DONATION',
  CREATE_DONATION_SUCCESS = 'app/Donations/CREATE_DONATION_SUCCESS',
  CREATE_DONATION_FAIL = 'app/Donations/CREATE_DONATION_FAIL',
  GET_DONATIONS_BY_ID = 'app/Donations/GET_DONATIONS_BY_ID',
  GET_DONATIONS_BY_ID_SUCCESS = 'app/Donations/GET_DONATIONS_BY_ID_SUCCESS',
  GET_DONATIONS_BY_ID_FAIL = 'app/Donations/GET_DONATIONS_BY_ID_FAIL',
  SELECT_CAUSE = 'app/Donations/SELECT_CAUSE',
  SELECT_DETAIL_VIEW = 'app/Donations/SELECT_DETAIL_VIEW',
}

export default DonationsConstants;
