enum ContactConstants {
  GET_CONTACT = 'donisto/Contact/GET_CONTACT',
  GET_CONTACT_SUCCESS = 'donisto/Contact/GET_CONTACT_SUCCESS',
  GET_CONTACT_FAIL = 'donisto/Contact/GET_CONTACT_FAIL',
  GET_CONTACT_ORGANIZATIONS = 'donisto/Contact/GET_CONTACT_ORGANIZATIONS',
  GET_CONTACT_ORGANIZATIONS_SUCCESS = 'donisto/Contact/GET_CONTACT_ORGANIZATIONS_SUCCESS',
  GET_CONTACT_ORGANIZATIONS_FAIL = 'donisto/Contact/GET_CONTACT_ORGANIZATIONS_FAIL',
  UPDATE_CONTACT = 'donisto/Contact/UPDATE_CONTACT',
  UPDATE_CONTACT_SUCCESS = 'donisto/Contact/UPDATE_CONTACT_SUCCESS',
  UPDATE_CONTACT_FAIL = 'donisto/Contact/UPDATE_CONTACT_FAIL',
  GET_ORG_NEWS_FEED = 'donisto/Contact/GET_ORG_NEWS_FEED',
  GET_ORG_NEWS_FEED_SUCCESS = 'donisto/Contact/GET_ORG_NEWS_FEED_SUCCESS',
  GET_ORG_NEWS_FEED_FAIL = 'donisto/Contact/GET_ORG_NEWS_FEED_FAIL'
}

export default ContactConstants;
