/*
 *
 * Cause constants
 *
 */

enum CauseConstants {
  CREATE_CAUSE_ACTION = 'app/Cause/CREATE_CAUSE_ACTION',
  CREATE_CAUSE_FAIL_ACTION = 'app/Cause/CREATE_CAUSE_FAIL_ACTION',
  CREATE_CAUSE_SUCCESS_ACTION = 'app/Cause/CREATE_CAUSE_SUCCESS_ACTION',
  GET_CAUSE_ACTION = 'app/Cause/GET_CAUSE_ACTION',
  GET_CAUSE_FAIL_ACTION = 'app/Cause/GET_CAUSE_FAIL_ACTION',
  GET_CAUSE_SUCCESS_ACTION = 'app/Cause/GET_CAUSE_SUCCESS_ACTION',
  GET_CAUSE_DETAIL_ACTION = 'app/Cause/GET_CAUSE_DETAIL_ACTION',
  GET_CAUSE_DETAIL_FAIL_ACTION = 'app/Cause/GET_CAUSE_DETAIL_FAIL_ACTION',
  GET_CAUSE_DETAIL_SUCCESS_ACTION = 'app/Cause/GET_CAUSE_DETAIL_SUCCESS_ACTION',
  GET_CAUSE_DETAIL_BY_ID_ACTION = 'app/Cause/GET_CAUSE_DETAIL_BY_ID_ACTION',
  GET_CAUSE_DETAIL_BY_ID_FAIL_ACTION = 'app/Cause/GET_CAUSE_DETAIL_BY_ID_FAIL_ACTION',
  GET_CAUSE_DETAIL_BY_ID_SUCCESS_ACTION = 'app/Cause/GET_CAUSE_DETAIL_BY_ID_SUCCESS_ACTION',
  TOGGLE_NEWSFEED_SELECT = 'app/Cause/TOGGLE_NEWSFEED_SELECT',
  SELECT_ORG_CREATE_CAUSE_ACTION = 'app/Cause/SELECT_ORG_CREATE_CAUSE_ACTION',
  GET_CONTACT_CAUSES_ACTION = 'app/Cause/GET_CONTACT_CAUSES_ACTION',
  GET_CONTACT_CAUSES_FAIL_ACTION = 'app/Cause/GET_CONTACT_CAUSES_FAIL_ACTION',
  GET_CONTACT_CAUSES_SUCCESS_ACTION = 'app/Cause/GET_CONTACT_CAUSES_SUCCESS_ACTION',
}

export default CauseConstants;
