/*
 *
 * Cause constants
 *
 */

enum CauseConstants {
  CREATE_CAUSE_ACTION = 'app/Cause/CREATE_CAUSE_ACTION',
  CREATE_CAUSE_FAIL_ACTION = 'app/Cause/CREATE_CAUSE_FAIL_ACTION',
  CREATE_CAUSE_SUCCESS_ACTION = 'app/Cause/CREATE_CAUSE_SUCCESS_ACTION',
  GET_CAUSE_ACTION = 'app/Cause/GET_CAUSE_ACTION',
  GET_CAUSE_FAIL_ACTION = 'app/Cause/GET_CAUSE_FAIL_ACTION',
  GET_CAUSE_SUCCESS_ACTION = 'app/Cause/GET_CAUSE_SUCCESS_ACTION',
  TOGGLE_NEWSFEED_SELECT = 'app/Cause/TOGGLE_NEWSFEED_SELECT',
}

export default CauseConstants;
